---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.10
  - name: debian-8.5
#  - name: centos-7.1

suites:
  - name: gibson
    run_list:
      - recipe[d-base::gibson]
    excludes:
      - debian-8.5
    attributes:
  - name: pi
    run_list:
      - recipe[d-base::default]
      - recipe[d-base::pi]
    attributes:
    excludes:
      - ubuntu-16.10
  - name: chefdk
    run_list:
      - recipe[d-base::chefdk]
      - recipe[d-base::_ruby]
    excludes:
      - debian-8.5
