---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-18.04

suites:
  - name: gibson
    run_list:
      - recipe[d-base::gibson]
#  - name: laptops
#    run_list:
#      - recipe[d-base::x61]
