name 'd-base'
maintainer 'Dayne Broderson'
maintainer_email 'broderson@gmail.com'
license 'MIT'
description 'Installs/Configures d-base'
long_description 'Installs/Configures d-base'
version '0.1.20'

depends 'chef-client', '~> 4.3.0'
depends 'resolver', '~> 1.3.0'
depends 'apt'
depends 'chef-sugar', '~> 3.1.0'
depends 'line', '~> 0.6.1'
depends 'packages', '~> 0.4.0'
depends 'openssh', '~> 1.4.0'
depends 'bash-CVE-2014-7169'
depends 'system', '~> 0.7.0'
