name 'd-base'
maintainer 'Dayne Broderson'
maintainer_email 'broderson@gmail.com'
license 'all_rights'
description 'Installs/Configures d-base'
long_description 'Installs/Configures d-base'
version '0.1.1'

depends 'chef-client'
depends 'resolver', '~> 1.3.0'
